spring.application.name=user-service
server.port=8086

# Discovery & Registry Configuration
eureka.client.enabled=true
spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}

# Central Config Server Import
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}